global:
  scrape_interval: 15s  # Intervalo padrão para coletar métricas

scrape_configs:
  - job_name: 'esg-risk-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['5002']  # # Porta interna da rede Docker

