global:
  scrape_interval: 15s  # Intervalo padrão para coletar métricas

scrape_configs:
  - job_name: 'esg-risk-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:5002']  # Porta mapeada da API

